Repository algorandfoundation/specs, pull requests merged in 2025-04, with the labels that each got.

#113 ci: add deployments and previews
  .github/workflows/deploy.yaml
Labels: ci-cd

#112 docs: reading guidelines
  src/SUMMARY.md
  src/reading-guidelines.md
Labels: non-normative

#115 docs: ABFT parameters
  src/SUMMARY.md
  src/abft-parameters.md
  src/abft.md
Labels: agreement

#114 docs: ABFT notation
  src/SUMMARY.md
  src/abft-notation.md
  src/abft.md
Labels: agreement

#117 docs: ABFT ledger
  src/SUMMARY.md
  src/abft-ledger.md
  src/abft.md
  src/reading-guidelines.md
Labels: agreement

#118 docs: ABFT messages
  src/SUMMARY.md
  src/abft-messages-bundles.md
  src/abft-messages-data-types.md
  src/abft-messages-proposals.md
  src/abft-messages-seed.md
  src/abft-messages-votes.md
  src/abft-messages.md
  src/abft.md
Labels: agreement

#131 docs: mdBook summary placeholder links
  src/SUMMARY.md
Labels: enhancement

#132 docs: ABFT non-normative, general concepts
  src/SUMMARY.md
  src/abft-nn-general-concepts.md
  src/abft-nn.md
Labels: agreement, non-normative

#134 docs: ABFT non-normative seed calculation
  src/SUMMARY.md
  src/abft-nn-seed-calculation.md
Labels: agreement, non-normative

#135 docs: ABFT non-normative agreement stages
  src/SUMMARY.md
  src/abft-nn-agreement-stages.md
  src/abft-nn-seed-calculation.md
Labels: agreement, non-normative

#136 docs: ABFT non-normative dynamic filter timeout
  src/SUMMARY.md
  src/abft-nn-dynamic-filter-timeout.md
Labels: agreement, non-normative

#137 docs: ABFT non-normative block proposal
  src/SUMMARY.md
  src/abft-nn-block-proposal.md
Labels: agreement, non-normative

#138 docs: ABFT non-normative soft vote
  src/SUMMARY.md
  src/abft-nn-dynamic-filter-timeout.md
  src/abft-nn-soft-vote.md
Labels: agreement, non-normative

#139 feat: text blocks
  src/.include/styles.md
  src/abft-nn-agreement-stages.md
  src/abft-nn-block-proposal.md
  src/abft-nn-dynamic-filter-timeout.md
  src/abft-nn-seed-calculation.md
  src/abft-nn-soft-vote.md
  src/reading-guidelines.md
Labels: enhancement

#140 fix: style file name
  src/abft-nn-agreement-stages.md
  src/abft-nn-block-proposal.md
  src/abft-nn-dynamic-filter-timeout.md
  src/abft-nn-seed-calculation.md
  src/abft-nn-soft-vote.md
  src/reading-guidelines.md
Labels: bug
