Repository algorandfoundation/specs, pull requests merged in 2025-08, with the labels that each got.

#195 docs: AVM normative
  src/SUMMARY.md
  src/avm/avm-appendix-b.md
  src/avm/avm-assembler.md
  src/avm/avm-constants.md
  src/avm/avm-execution-modes.md
  src/avm/avm-mode-applications.md
  src/avm/avm-mode-logic-signatures.md
  src/avm/avm-nn-run-times.md
  src/avm/avm-operations.md
  src/avm/avm-ops-arithmetic-and-logic.md
  src/avm/avm-ops-byte-array-manipulation.md
  src/avm/avm-ops-cryptography.md
  src/avm/avm-ops-fields.md
  src/avm/avm-ops-flow-conrol.md
  src/avm/avm-ops-inner-transactions.md
  src/avm/avm-ops-loading-values.md
  src/avm/avm-ops-state-access.md
  src/avm/avm-scratch-space.md
  src/avm/avm-stack.md
  src/avm/avm-teal-opcodes.md
  src/avm/avm-versioning.md
  src/avm/avm.md
Labels: avm

#194 add description of new SHA-512 usage
  dev/crypto.md
  dev/ledger.md
Labels: crypto, ledger

#116 docs: ABFT players
  src/SUMMARY.md
  src/abft-participants.md
  src/abft.md
Labels: agreement

#125 docs: ABFT state transitions
  src/SUMMARY.md
  src/abft-state-transitions-garbage-collection.md
  src/abft-state-transitions-new-period.md
  src/abft-state-transitions-new-round.md
  src/abft-state-transitions-new-step.md
  src/abft-state-transitions.md
  src/abft.md
Labels: agreement

#128 docs: ABFT broadcast rules
  src/SUMMARY.md
  src/abft-broadcast-rules-certifying.md
  src/abft-broadcast-rules-commit.md
  src/abft-broadcast-rules-fast-recovery.md
  src/abft-broadcast-rules-filtering.md
  src/abft-broadcast-rules-proposals.md
  src/abft-broadcast-rules-recovery.md
  src/abft-broadcast-rules-reproposals.md
  src/abft-broadcast-rules-resync.md
  src/abft-broadcast-rules.md
  src/abft.md
Labels: agreement

#187 Described application version and reject version
  dev/TEAL.md
  dev/TEAL_opcodes.md
  dev/ledger.md
Labels: avm, transactions, ledger

#204 falcon_verify opcode.
  dev/TEAL.md
  dev/TEAL_opcodes.md
Labels: avm

#123 docs: ABFT state machine and player state
  src/SUMMARY.md
  src/abft-player-state.md
  src/abft-state-machine.md
  src/abft.md
Labels: agreement

#197 build: no longer fail for outside PRs
  .github/workflows/deploy.yaml
Labels: ci-cd

#209 chore: auto include update
  src/.include/auto-avm-ops-inner-transactions.md
  src/.include/auto-avm-ops-state-access.md
  src/.include/auto/avm-fields-account.md
  src/.include/auto/avm-fields-application.md
  src/.include/auto/avm-fields-asset-holding.md
  src/.include/auto/avm-fields-asset-params.md
  src/.include/auto/avm-fields-global.md
  src/.include/auto/avm-fields-txn-array.md
  src/.include/auto/avm-fields-txn-scalar.md
  src/.include/auto/avm-ops-arithmetic-and-logic.md
  src/.include/auto/avm-ops-bitwise.md
  src/.include/auto/avm-ops-byte-arithmetic.md
  src/.include/auto/avm-ops-byte-array-manipulation.md
  src/.include/auto/avm-ops-cryptography.md
  src/.include/auto/avm-ops-flow-control.md
  src/.include/auto/avm-ops-inner-transactions.md
  src/.include/auto/avm-ops-loading-values.md
  src/.include/auto/avm-ops-state-access-account.md
  src/.include/auto/avm-ops-state-access-app.md
  src/.include/auto/avm-ops-state-access-asset.md
  src/.include/auto/avm-ops-state-access-block.md
  src/.include/auto/avm-ops-state-access-box.md
  src/.include/auto/avm-teal-opcodes.md
  src/.include/auto/avm-version
  src/avm/avm-appendix-a.md
  src/avm/avm-ops-arithmetic-and-logic.md
  src/avm/avm-ops-byte-array-manipulation.md
  src/avm/avm-ops-cryptography.md
  src/avm/avm-ops-fields.md
  src/avm/avm-ops-flow-control.md
  src/avm/avm-ops-inner-transactions.md
  src/avm/avm-ops-loading-values.md
  src/avm/avm-ops-state-access.md
  src/avm/avm-versioning.md
Labels: enhancement

#130 docs: ABFT fixes and LaTeX refactor
  src/abft-ledger.md
  src/abft-messages-bundles.md
  src/abft-messages-data-types.md
  src/abft-messages-proposals.md
  src/abft-messages-seed.md
  src/abft-messages-votes.md
  src/abft-notation.md
  src/abft-parameters.md
  src/abft/abft-nn-context-tuple.md
  src/abft/abft-nn-dynamic-filter-timeout.md
  src/abft/abft-nn-seed-calculation.md
Labels: enhancement, agreement, fix

#198 docs: add SHA-512 fields
  src/SUMMARY.md
  src/avm/avm-mode-logic-signatures.md
  src/avm/avm-ops-inner-transactions.md
  src/crypto/crypto-sha256.md
  src/crypto/crypto-sha512-256.md
  src/crypto/crypto-sha512.md
  src/ledger/ledger-block.md
  src/ledger/ledger-txn-sequence.md
Labels: crypto, ledger
